### ISSUE TITLE
Infinitely draining stats

### ISSUE THREAD

**Issue by Dir7yHobo** [Wurmatron/WurmTweaks#11]
Relogging while in the mining world on grumpycraft seems to cause infinitely draining hunger, thirst, and nutrition types. Relogging while in the normal world seems to fix the drainage of hunger, but the nutrition wont stop draining, so health is locked around 50.
[Original thread](http://www.grumpycraft.com/forum/m/13623199/viewthread/27331552-wurmcraft-stats-infinitely-draining)

**Comment by Wurmatron** [comment]
This has been a long known issue with the mining world. I know that it has to do something with how terrafirmacraft (tfc) does not exactly allow "new dimensions". The only fix that i am currently able to create would be one that makes it so if the player aka you logs out of the mining world it would force you to use the teleporter as you logged out. This would still not fix the issue with anyone inventory in the mining world becoming desynced. Also the infinitely draining stats are caused due to there being no data related to your "stats" inside your player file because they are not synced after the inital entry into the mining world, they will however stay loaded in the servers R.A.M. and if you go back into the overworld without unloading your player on the server then the serer still has your "stats" and is able to resync them.

**Comment by Wurmatron** [comment]
Should be semi-fixed for 0.71. Disabled players ability to logout in mining world by teleporting on logout to overworld if in an different dimension
